# ============================================================================
# build_diamond.tcl - Lattice Diamond batch build for Code-SDR V2.
#
# Run with the Diamond TCL console:
#   D:\Lattice\bin\nt64\pnmainc.exe verilog\build_diamond.tcl
#
# Edit MODE below (0 = raw streamer, 1 = on-FPGA FFT) or override from the
# command line. Produces the bitstream, the utilisation report and the timing
# report under build/diamond/<mode>/.
#
# NOTE: this is staged and unrun - it has never executed, because Diamond needs
# a licence (see GATEWARE.md "Licence path"). Expect to adjust primitive-related
# synthesis options on the first real run.
# ============================================================================

# ---------------------------------------------------------------- configuration
set MODE        0
set SAMPLE_BITS 8
set DECIM       1
set FFT_N       1024

set DEVICE      "LIF-MD6000-6JMG80I"
set TOP         "v2_top"
set ROOT        [file normalize [file join [pwd]]]

if {$MODE == 1} {
    set BUILD "build/diamond/fft"
    set TOPW  "v2_top_fft"
} else {
    set BUILD "build/diamond/raw"
    set TOPW  "v2_top_raw"
}

file mkdir $BUILD

# ------------------------------------------------------------------- sources
set RTL {
    verilog/v2_top.v
    verilog/v2_clock_pll.v
    verilog/v2_phy_manager.v
    verilog/v2_mdio_master.v
    verilog/v2_rgmii.v
    verilog/v2_raw_path.v
    verilog/v2_cdc_fifo.v
    verilog/v2_udp_ip_tx.v
    verilog/v2_eth_mac_tx.v
    verilog/v2_telemetry.v
    verilog/v2_spi_regs.v
    verilog/v2_cic_decimator.v
    verilog/v2_fft1024.v
    verilog/v2_fft_packetizer.v
}

# A generated wrapper pins the compile-time parameters, since Diamond sets
# Verilog *macros* easily but not module parameters.
set wrap [open "$BUILD/$TOPW.v" w]
puts $wrap "// generated by build_diamond.tcl - do not edit"
puts $wrap "module $TOPW ("
puts $wrap "    input  wire        rst_n,"
puts $wrap "    input  wire        clk_100m_in,"
puts $wrap "    input  wire \[9:0\]  adc_data,"
puts $wrap "    input  wire        adc_ovr,"
puts $wrap "    input  wire        spi_clk,"
puts $wrap "    input  wire        spi_mosi,"
puts $wrap "    input  wire        spi_cs_n,"
puts $wrap "    output wire        spi_miso,"
puts $wrap "    output wire \[3:0\]  rgmii_txd,"
puts $wrap "    output wire        rgmii_tx_ctl,"
puts $wrap "    output wire        rgmii_txc,"
puts $wrap "    input  wire \[3:0\]  rgmii_rxd,"
puts $wrap "    input  wire        rgmii_rx_ctl,"
puts $wrap "    input  wire        rgmii_rxc,"
puts $wrap "    output wire        mdc,"
puts $wrap "    inout  wire        mdio,"
puts $wrap "    input  wire        phy_int_n"
puts $wrap ");"
puts $wrap "    v2_top #("
puts $wrap "        .MODE($MODE), .SAMPLE_BITS($SAMPLE_BITS),"
puts $wrap "        .DECIM($DECIM), .FFT_N($FFT_N)"
puts $wrap "    ) u_top ("
puts $wrap "        .rst_n(rst_n), .clk_100m_in(clk_100m_in),"
puts $wrap "        .adc_data(adc_data), .adc_ovr(adc_ovr),"
puts $wrap "        .spi_clk(spi_clk), .spi_mosi(spi_mosi),"
puts $wrap "        .spi_cs_n(spi_cs_n), .spi_miso(spi_miso),"
puts $wrap "        .rgmii_txd(rgmii_txd), .rgmii_tx_ctl(rgmii_tx_ctl),"
puts $wrap "        .rgmii_txc(rgmii_txc), .rgmii_rxd(rgmii_rxd),"
puts $wrap "        .rgmii_rx_ctl(rgmii_rx_ctl), .rgmii_rxc(rgmii_rxc),"
puts $wrap "        .mdc(mdc), .mdio(mdio), .phy_int_n(phy_int_n)"
puts $wrap "    );"
puts $wrap "endmodule"
close $wrap

# ------------------------------------------------------------------- project
prj_project new -name "codesdr_$TOPW" -impl impl1 \
    -dev $DEVICE -synthesis "lse" -location "$BUILD"

foreach f $RTL { prj_src add $f }
prj_src add "$BUILD/$TOPW.v"
prj_src add verilog/v2_top.lpf
prj_src add verilog/twiddle_real.mem
prj_src add verilog/twiddle_imag.mem
prj_src add verilog/window_coeff.mem

prj_impl option top $TOPW
prj_impl option -hdl_param -add "MODE=$MODE"

# --------------------------------------------------------------------- build
prj_run Synthesis -impl impl1
prj_run Map       -impl impl1
prj_run PAR       -impl impl1
prj_run Export    -impl impl1

# ------------------------------------------------------------------- reports
prj_run Report -impl impl1

puts "=== build complete: $BUILD ==="
puts "=== check the *.rpt files for utilisation and timing ==="

prj_project save
prj_project close
