`default_nettype none
// ============================================================================
// FFT Processor Module - Streaming Radix-2 DIF SDF Architecture
// ============================================================================
// Accepts one complex sample per clk when data_valid is asserted. There are no
// load/process/output dead cycles: after pipeline fill, one natural-order bin is
// produced per input sample. Twiddles are loaded from synthesis-friendly .mem
// ROMs generated by tools/build_system/generate_twiddles.py.
// ============================================================================

`timescale 1ns/1ps

module fft_processor #(
    parameter FFT_SIZE = 1024,
    parameter DATA_WIDTH = 24,
    parameter TWIDDLE_WIDTH = 16
) (
    input  wire        clk,
    input  wire        rst_n,

    input  wire [DATA_WIDTH-1:0] real_in,
    input  wire [DATA_WIDTH-1:0] imag_in,
    input  wire        data_valid,

    output wire [DATA_WIDTH-1:0] real_out,
    output wire [DATA_WIDTH-1:0] imag_out,
    output wire        fft_valid,
    output wire [$clog2(FFT_SIZE)-1:0] fft_index,
    output wire [31:0] frame_count,
    output wire        overflow_flag,
    output wire        processing_active
);

    localparam ADDR_WIDTH = $clog2(FFT_SIZE);
    localparam STAGES = ADDR_WIDTH;
    localparam PIPELINE_LATENCY = (FFT_SIZE - 1) + STAGES;

    initial begin
        if (FFT_SIZE != 1024) begin
            $error("fft_processor issue-12 implementation is fixed to FFT_SIZE=1024");
        end
    end

    reg signed [TWIDDLE_WIDTH-1:0] twiddle_real [0:(FFT_SIZE/2)-1];
    reg signed [TWIDDLE_WIDTH-1:0] twiddle_imag [0:(FFT_SIZE/2)-1];
    initial begin
        $readmemh("twiddle_real.mem", twiddle_real);
        $readmemh("twiddle_imag.mem", twiddle_imag);
    end

    reg [ADDR_WIDTH-1:0] in_count;
    reg [31:0] frame_counter;
    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            in_count <= {ADDR_WIDTH{1'b0}};
            frame_counter <= 32'd0;
        end else if (data_valid) begin
            if (in_count == FFT_SIZE-1) begin
                in_count <= {ADDR_WIDTH{1'b0}};
                frame_counter <= frame_counter + 1'b1;
            end else begin
                in_count <= in_count + 1'b1;
            end
        end
    end

    wire signed [DATA_WIDTH-1:0] stage_r [0:STAGES];
    wire signed [DATA_WIDTH-1:0] stage_i [0:STAGES];
    wire [ADDR_WIDTH-1:0] stage_count [0:STAGES];
    wire [31:0] stage_frame [0:STAGES];
    wire stage_valid [0:STAGES];

    assign stage_r[0] = data_valid ? $signed(real_in) : {DATA_WIDTH{1'b0}};
    assign stage_i[0] = data_valid ? $signed(imag_in) : {DATA_WIDTH{1'b0}};
    assign stage_count[0] = in_count;
    assign stage_frame[0] = frame_counter;
    assign stage_valid[0] = data_valid;

    reg [ADDR_WIDTH-1:0] count_pipe [0:PIPELINE_LATENCY-1];
    reg [31:0] frame_pipe [0:PIPELINE_LATENCY-1];
    reg [PIPELINE_LATENCY-1:0] valid_pipe;
    integer p;

    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            valid_pipe <= {PIPELINE_LATENCY{1'b0}};
            for (p = 0; p < PIPELINE_LATENCY; p = p + 1) begin
                count_pipe[p] <= {ADDR_WIDTH{1'b0}};
                frame_pipe[p] <= 32'd0;
            end
        end else begin
            valid_pipe <= {valid_pipe[PIPELINE_LATENCY-2:0], data_valid};
            count_pipe[0] <= in_count;
            frame_pipe[0] <= frame_counter;
            for (p = 1; p < PIPELINE_LATENCY; p = p + 1) begin
                count_pipe[p] <= count_pipe[p-1];
                frame_pipe[p] <= frame_pipe[p-1];
            end
        end
    end

    wire [STAGES-1:0] stage_overflow;

    genvar s;
    generate
        for (s = 0; s < STAGES; s = s + 1) begin : sdf_stage
            localparam DELAY = 1 << (STAGES - 1 - s);
            reg signed [DATA_WIDTH-1:0] delay_real [0:DELAY-1];
            reg signed [DATA_WIDTH-1:0] delay_imag [0:DELAY-1];

            wire [ADDR_WIDTH-1:0] ctrl_count = stage_count[s];
            wire bf_state = ctrl_count[STAGES-1-s];
            wire signed [DATA_WIDTH-1:0] x_r = stage_r[s];
            wire signed [DATA_WIDTH-1:0] x_i = stage_i[s];
            wire signed [DATA_WIDTH-1:0] d_r = delay_real[DELAY-1];
            wire signed [DATA_WIDTH-1:0] d_i = delay_imag[DELAY-1];

            wire signed [DATA_WIDTH:0] full_s_r = $signed(d_r) + $signed(x_r);
            wire signed [DATA_WIDTH:0] full_s_i = $signed(d_i) + $signed(x_i);
            wire signed [DATA_WIDTH:0] full_d_r = $signed(d_r) - $signed(x_r);
            wire signed [DATA_WIDTH:0] full_d_i = $signed(d_i) - $signed(x_i);

            wire sum_ov_r = (full_s_r[DATA_WIDTH] != full_s_r[DATA_WIDTH-1]);
            wire sum_ov_i = (full_s_i[DATA_WIDTH] != full_s_i[DATA_WIDTH-1]);
            wire diff_ov_r = (full_d_r[DATA_WIDTH] != full_d_r[DATA_WIDTH-1]);
            wire diff_ov_i = (full_d_i[DATA_WIDTH] != full_d_i[DATA_WIDTH-1]);

            wire signed [DATA_WIDTH-1:0] sum_r = full_s_r[DATA_WIDTH:1];
            wire signed [DATA_WIDTH-1:0] sum_i = full_s_i[DATA_WIDTH:1];
            wire signed [DATA_WIDTH-1:0] diff_r = full_d_r[DATA_WIDTH:1];
            wire signed [DATA_WIDTH-1:0] diff_i = full_d_i[DATA_WIDTH:1];

            wire [ADDR_WIDTH-1:0] tw_idx_full = (ctrl_count << s);
            wire [ADDR_WIDTH-2:0] tw_idx = tw_idx_full[ADDR_WIDTH-2:0];
            wire signed [TWIDDLE_WIDTH-1:0] w_r = twiddle_real[tw_idx];
            wire signed [TWIDDLE_WIDTH-1:0] w_i = twiddle_imag[tw_idx];

            wire signed [DATA_WIDTH+TWIDDLE_WIDTH-1:0] p_rr = $signed(diff_r) * $signed(w_r);
            wire signed [DATA_WIDTH+TWIDDLE_WIDTH-1:0] p_ii = $signed(diff_i) * $signed(w_i);
            wire signed [DATA_WIDTH+TWIDDLE_WIDTH-1:0] p_ri = $signed(diff_r) * $signed(w_i);
            wire signed [DATA_WIDTH+TWIDDLE_WIDTH-1:0] p_ir = $signed(diff_i) * $signed(w_r);
            wire signed [DATA_WIDTH+TWIDDLE_WIDTH:0] rot_r_wide = ($signed(p_rr) - $signed(p_ii)) >>> (TWIDDLE_WIDTH-1);
            wire signed [DATA_WIDTH+TWIDDLE_WIDTH:0] rot_i_wide = ($signed(p_ri) + $signed(p_ir)) >>> (TWIDDLE_WIDTH-1);
            wire signed [DATA_WIDTH-1:0] rot_r = rot_r_wide[DATA_WIDTH-1:0];
            wire signed [DATA_WIDTH-1:0] rot_i = rot_i_wide[DATA_WIDTH-1:0];

            wire rot_ov_r = (rot_r_wide[DATA_WIDTH+TWIDDLE_WIDTH:DATA_WIDTH-1] !=
                             {(TWIDDLE_WIDTH+2){rot_r_wide[DATA_WIDTH-1]}});
            wire rot_ov_i = (rot_i_wide[DATA_WIDTH+TWIDDLE_WIDTH:DATA_WIDTH-1] !=
                             {(TWIDDLE_WIDTH+2){rot_i_wide[DATA_WIDTH-1]}});
            assign stage_overflow[s] = stage_valid[s] &&
                (sum_ov_r | sum_ov_i | diff_ov_r | diff_ov_i | rot_ov_r | rot_ov_i);

            reg signed [DATA_WIDTH-1:0] next_r;
            reg signed [DATA_WIDTH-1:0] next_i;
            reg [ADDR_WIDTH-1:0] next_count;
            reg [31:0] next_frame;
            reg next_valid;
            integer d;

            always @(posedge clk or negedge rst_n) begin
                if (!rst_n) begin
                    next_r <= {DATA_WIDTH{1'b0}};
                    next_i <= {DATA_WIDTH{1'b0}};
                    next_count <= {ADDR_WIDTH{1'b0}};
                    next_frame <= 32'd0;
                    next_valid <= 1'b0;
                    for (d = 0; d < DELAY; d = d + 1) begin
                        delay_real[d] <= {DATA_WIDTH{1'b0}};
                        delay_imag[d] <= {DATA_WIDTH{1'b0}};
                    end
                end else begin
                    if (!bf_state) begin
                        delay_real[0] <= x_r;
                        delay_imag[0] <= x_i;
                        next_r <= d_r;
                        next_i <= d_i;
                    end else begin
                        delay_real[0] <= rot_r;
                        delay_imag[0] <= rot_i;
                        next_r <= sum_r;
                        next_i <= sum_i;
                    end
                    next_count <= ctrl_count;
                    next_frame <= stage_frame[s];
                    next_valid <= stage_valid[s];

                    for (d = 1; d < DELAY; d = d + 1) begin
                        delay_real[d] <= delay_real[d-1];
                        delay_imag[d] <= delay_imag[d-1];
                    end
                end
            end

            assign stage_r[s+1] = next_r;
            assign stage_i[s+1] = next_i;
            assign stage_count[s+1] = next_count;
            assign stage_frame[s+1] = next_frame;
            assign stage_valid[s+1] = next_valid;
        end
    endgenerate

    reg frame_overflow;
    reg output_overflow;
    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            frame_overflow <= 1'b0;
            output_overflow <= 1'b0;
        end else begin
            if (data_valid && in_count == {ADDR_WIDTH{1'b0}}) begin
                frame_overflow <= |stage_overflow;
            end else if (data_valid) begin
                frame_overflow <= frame_overflow | (|stage_overflow);
            end

            if (valid_pipe[PIPELINE_LATENCY-1] &&
                count_pipe[PIPELINE_LATENCY-1] == {ADDR_WIDTH{1'b0}}) begin
                output_overflow <= frame_overflow | (|stage_overflow);
            end
        end
    end

    function [ADDR_WIDTH-1:0] bit_rev;
        input [ADDR_WIDTH-1:0] addr;
        integer j;
        begin
            for (j = 0; j < ADDR_WIDTH; j = j + 1) begin
                bit_rev[ADDR_WIDTH-1-j] = addr[j];
            end
        end
    endfunction

    assign real_out = stage_r[STAGES];
    assign imag_out = stage_i[STAGES];
    assign fft_valid = valid_pipe[PIPELINE_LATENCY-1];
    assign fft_index = bit_rev(count_pipe[PIPELINE_LATENCY-1]);
    assign frame_count = frame_pipe[PIPELINE_LATENCY-1];
    assign overflow_flag = output_overflow;
    assign processing_active = |valid_pipe || data_valid;

endmodule
`default_nettype wire
