// ============================================================================
// v2_clock_pll - 100 MHz board reference -> 125 MHz Ethernet clock.
//
// The V2 board has exactly one clock tree (SiT8209 100 MHz -> CDCLVC1104 fanout)
// and no 125 MHz source, so RGMII's 125 MHz must come from the CrossLink PLL.
// CrossLink has one general-purpose PLL, which is exactly what this uses.
//
// In simulation a behavioural 125 MHz source is generated so the datapath can be
// verified. In hardware the body must be the Diamond-generated PLL (Clarity
// Designer / EHXPLLL) with the same port names; that primitive is deliberately
// not hand-written here because its exact parameter set must come from the
// vendor tool, not be guessed.
// ============================================================================

`timescale 1ns/1ps
`default_nettype none

module v2_clock_pll (
    input  wire clk_100m_in,
    input  wire rst_n,
    output wire clk_125m_eth,
    output wire locked
);

`ifdef V2_USE_VENDOR_PLL
    // ---------------------------------------------------------------- hardware
    // Generated by Diamond (Clarity Designer) for LIF-MD6000-6JMG80I:
    //   CLKI = 100 MHz, CLKOP = 125 MHz (5/4), RESET driven by ~rst_n.
    // The instance must expose CLKOP as clk_125m_eth and LOCK as locked.
    v2_pll_125m u_pll (
        .CLKI   (clk_100m_in),
        .RESET  (~rst_n),
        .CLKOP  (clk_125m_eth),
        .LOCK   (locked)
    );
`else
    // ------------------------------------------------------------- simulation
    reg clk_r = 1'b0;
    always #4 clk_r = ~clk_r;                 // 125 MHz

    reg [4:0] lock_cnt;
    always @(posedge clk_r or negedge rst_n) begin
        if (!rst_n) lock_cnt <= 5'd0;
        else if (lock_cnt != 5'd31) lock_cnt <= lock_cnt + 5'd1;
    end

    assign clk_125m_eth = clk_r;
    assign locked       = (lock_cnt == 5'd31);
`endif

endmodule

`default_nettype wire
