// ============================================================================
// v2_rgmii - GMII (8-bit, single edge) <-> RGMII (4-bit, DDR) conversion.
//
// The KSZ9031 on this board is RGMII-only (HARDWARE.md section 7); there are no
// GMII error/CRS/COL nets, so the internal side is a plain 8-bit byte interface
// clocked at 125 MHz (exactly 1000 Mbps).
//
// Two implementations:
//   * default (simulation): behavioural edge processes, used by the testbenches.
//   * V2_USE_VENDOR_DDR: Lattice DDR input/output primitives for hardware.
//
// !!! HARDWARE CONSTRAINT TO CONFIRM FIRST !!!
// CrossLink GPIO DDR is only available in Bank 1 and Bank 2 (Bank 0 is
// SDR-only). The RGMII pins are balls E1,E2,F1,F2,J3,J7 (TX) and K8,J5,K10,K4,
// K5,K6 (RX); whether those land in Bank 1/2 must be checked against the
// CrossLink pinout (FPGA-DS-02007 / the LIF-MD6000 pinout spreadsheet). If any
// RGMII pin is in Bank 0, RGMII cannot work on that pin and the pin assignment
// has to change.
//
// Primitive references: FPGA-TN-02016 (CrossLink sysI/O Usage Guide) and
// FPGA-TN-02012 (CrossLink High-Speed I/O Interface). The exact primitive names
// and port lists must be confirmed against those guides or regenerated by
// Clarity Designer before the first build.
// ============================================================================

`timescale 1ns/1ps
`default_nettype none

module v2_rgmii (
    input  wire       rst_n,

    // RGMII pins to the KSZ9031
    input  wire       rgmii_rxc,
    input  wire [3:0] rgmii_rxd,
    input  wire       rgmii_rx_ctl,
    output wire       rgmii_txc,
    output wire [3:0] rgmii_txd,
    output wire       rgmii_tx_ctl,

    // Internal GMII-style byte interface
    input  wire       clk_tx,          // 125 MHz from the PLL
    input  wire [7:0] gmii_tx_d,
    input  wire       gmii_tx_en,
    output reg  [7:0] gmii_rx_d,
    output reg        gmii_rx_dv
);

`ifdef V2_USE_VENDOR_DDR
    // ---------------------------------------------------------- TX (hardware)
    // DDR output cells: D0 on the rising edge, D1 on the falling edge, which is
    // exactly the RGMII nibble order (bits [3:0] then [7:4]).
    genvar i;
    generate
        for (i = 0; i < 4; i = i + 1) begin : g_txd
            ODDRX1F u_oddr (
                .D0   (gmii_tx_d[i]),
                .D1   (gmii_tx_d[i+4]),
                .SCLK (clk_tx),
                .RST  (~rst_n),
                .Q    (rgmii_txd[i])
            );
        end
    endgenerate

    ODDRX1F u_oddr_ctl (
        .D0 (gmii_tx_en), .D1 (gmii_tx_en),
        .SCLK(clk_tx), .RST(~rst_n), .Q(rgmii_tx_ctl)
    );

    // TXC is the 125 MHz clock on a clock-capable output. It must be driven from
    // a global clock net; the clock/data skew is handled by the KSZ9031 internal
    // delay registers (programmed by v2_phy_manager), not by added FPGA skew.
    // TODO(hw): route this through a dedicated clock output with an output-delay
    // constraint rather than a fabric net.
    assign rgmii_txc = clk_tx;

    // ---------------------------------------------------------- RX (hardware)
    wire [3:0] rx_lo, rx_hi;
    wire       ctl_lo, ctl_hi;

    generate
        for (i = 0; i < 4; i = i + 1) begin : g_rxd
            IDDRX1F u_iddr (
                .D    (rgmii_rxd[i]),
                .SCLK (rgmii_rxc),
                .RST  (~rst_n),
                .Q0   (rx_lo[i]),
                .Q1   (rx_hi[i])
            );
        end
    endgenerate

    IDDRX1F u_iddr_ctl (
        .D (rgmii_rx_ctl), .SCLK(rgmii_rxc), .RST(~rst_n),
        .Q0(ctl_lo), .Q1(ctl_hi)
    );

    // Assemble the byte on the falling edge so the high nibble pairs with the
    // low nibble of the SAME byte (assembling on the rising edge would mix in
    // the previous byte's high nibble - the bug the loopback test caught in the
    // behavioural version).
    always @(negedge rgmii_rxc or negedge rst_n)
        if (!rst_n) begin
            gmii_rx_d  <= 8'h00;
            gmii_rx_dv <= 1'b0;
        end else begin
            gmii_rx_d  <= {rx_hi, rx_lo};
            gmii_rx_dv <= ctl_lo & ctl_hi;
        end

`else
    // ------------------------------------------------------ TX (behavioural)
    // Latch the byte ONCE per cycle and drive both nibbles from that single
    // register. Sampling gmii_tx_d directly on each edge would read the old byte
    // on the rising edge and the new byte on the falling edge (the source
    // updates on the same clock), splitting every byte across two frames - which
    // the loopback test caught.
    reg [7:0] tx_byte;
    reg       tx_en_r;

    always @(posedge clk_tx or negedge rst_n)
        if (!rst_n) begin tx_byte <= 8'h00; tx_en_r <= 1'b0; end
        else        begin tx_byte <= gmii_tx_d; tx_en_r <= gmii_tx_en; end

    // rising edge -> bits [3:0], falling edge -> bits [7:4], same byte.
    assign rgmii_txd    = clk_tx ? tx_byte[3:0] : tx_byte[7:4];
    assign rgmii_tx_ctl = tx_en_r;
    assign rgmii_txc    = clk_tx;

    // ------------------------------------------------------ RX (behavioural)
    // Low nibble is present on the rising edge, high nibble on the falling edge.
    // The byte must therefore be assembled on the FALLING edge.
    reg [3:0] rx_lo;
    reg       ctl_lo;

    always @(posedge rgmii_rxc or negedge rst_n)
        if (!rst_n) begin rx_lo <= 4'h0; ctl_lo <= 1'b0; end
        else        begin rx_lo <= rgmii_rxd; ctl_lo <= rgmii_rx_ctl; end

    always @(negedge rgmii_rxc or negedge rst_n)
        if (!rst_n) begin
            gmii_rx_d <= 8'h00;
            gmii_rx_dv<= 1'b0;
        end else begin
            gmii_rx_d <= {rgmii_rxd, rx_lo};
            gmii_rx_dv<= ctl_lo & rgmii_rx_ctl;
        end
`endif

endmodule

`default_nettype wire
