/* Generated by Yosys 0.56+30 (git sha1 407d42511, g++ 11.4.0-1ubuntu1~22.04.2 -fPIC -O3) */

module clock_manager(clk_100m_in, rst_n, clk_600m, clk_1200m_fft, clk_125m_eth, clk_250m_eth, clk_105m_adc, locked);
  input clk_100m_in;
  wire clk_100m_in;
  input rst_n;
  wire rst_n;
  output clk_600m;
  wire clk_600m;
  output clk_1200m_fft;
  wire clk_1200m_fft;
  output clk_125m_eth;
  wire clk_125m_eth;
  output clk_250m_eth;
  wire clk_250m_eth;
  output clk_105m_adc;
  wire clk_105m_adc;
  output locked;
  wire locked;
  assign clk_105m_adc = clk_100m_in;
  assign clk_1200m_fft = clk_100m_in;
  assign clk_125m_eth = clk_100m_in;
  assign clk_250m_eth = clk_100m_in;
  assign clk_600m = clk_100m_in;
  assign locked = rst_n;
endmodule
