#!/usr/bin/env python3
"""
Extract the FPGA pin map from the KiCad PCB and generate a Diamond .lpf.

Parses hardware/v2/Code-SDR-V2.kicad_pcb for the U20 footprint (the
LIF-MD6000-6JMG80I), reads each pad's ball designator and the net it lands on,
and emits verilog/v2_top_generated.lpf with a LOCATE for every v2_top port.

This is derived from copper, not from the legacy RTL - it is the same source of
truth HARDWARE.md uses.

Usage:
  python tools/gen_lpf.py                 # write verilog/v2_top_generated.lpf
  python tools/gen_lpf.py --table         # print the ball -> net table
"""

import argparse
import os
import re
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PCB = os.path.join(REPO, "hardware", "v2", "Code-SDR-V2.kicad_pcb")
OUT = os.path.join(REPO, "verilog", "v2_top_generated.lpf")
FPGA_REF = "U20"

# v2_top port -> the PCB net each bit connects to.
# Order matters: the index in the list is the bit index.
PORT_NETS = {
    "clk_100m_in": ["ADC_CLK"],
    "adc_data":    ["ADC_D%d" % i for i in range(10)],
    "adc_ovr":     ["ADC_OR"],
    "rgmii_txd":   ["RGMII_TXD%d_FPGA" % i for i in range(4)],
    "rgmii_tx_ctl":["RGMII_TX_EN_FPGA"],
    "rgmii_txc":   ["RGMII_TXC_FPGA"],
    "rgmii_rxd":   ["RGMII_RXD%d_FPGA" % i for i in range(4)],
    "rgmii_rx_ctl":["RGMII_RX_DV_FPGA"],
    "rgmii_rxc":   ["RGMII_RXC_FPGA"],
    "mdc":         ["MDC"],
    "mdio":        ["MDIO"],
    "phy_int_n":   ["PHY_INT_N"],
    "spi_mosi":    ["FPGA_SPI_MOSI"],
    "spi_miso":    ["FPGA_SPI_MISO"],
    "spi_cs_n":    ["FPGA_SPI_CS_N"],
    "spi_clk":     ["FPGA_SPI_SCK"],
    "rst_n":       ["FPGA_RESET_N"],
}

# nets that are configuration/RP2040-owned, not user I/O for the gateware
NOT_USER_IO = {"FPGA_CDONE", "FPGA_SPI_SCK_MCU"}


def parse_footprint_pads(path, ref):
    """Return {pad_name: net_name} for the footprint whose Reference property == ref."""
    txt = open(path, "r", encoding="utf-8", errors="replace").read()

    # find the footprint block containing this reference
    best = None
    for m in re.finditer(r'\(footprint\s+"[^"]+"', txt):
        start = m.start()
        # scan to the matching close paren
        depth = 0
        i = start
        while i < len(txt):
            if txt[i] == '(':
                depth += 1
            elif txt[i] == ')':
                depth -= 1
                if depth == 0:
                    break
            i += 1
        block = txt[start:i]
        if re.search(r'\(property\s+"Reference"\s+"%s"' % re.escape(ref), block):
            best = block
            break

    if best is None:
        raise SystemExit(f"footprint with Reference {ref} not found")

    pads = {}
    for pm in re.finditer(r'\(pad\s+"([^"]+)"(.*?)(?=\(pad\s+"|\Z)', best, re.S):
        name, body = pm.group(1), pm.group(2)
        nm = re.search(r'\(net\s+\d+\s+"([^"]*)"\)', body)
        if nm:
            pads[name] = nm.group(1)
        else:
            pads[name] = None
    return pads


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--table", action="store_true")
    args = ap.parse_args()

    pads = parse_footprint_pads(PCB, FPGA_REF)
    net2ball = {v: k for k, v in pads.items() if v}

    if args.table:
        for ball in sorted(net2ball):
            print(f"  {net2ball[ball]:>8}  {ball}")
        return 0

    lines = []
    missing = []
    lines.append("# ============================================================================")
    lines.append("# v2_top_generated.lpf - GENERATED by tools/gen_lpf.py from")
    lines.append("# hardware/v2/Code-SDR-V2.kicad_pcb (footprint U20, LIF-MD6000-6JMG80I).")
    lines.append("# Do not edit by hand; re-run the generator after any PCB change.")
    lines.append("# ============================================================================")
    lines.append("")

    for port, nets in PORT_NETS.items():
        for i, net in enumerate(nets):
            ball = net2ball.get(net)
            if ball is None:
                missing.append(f"{port}[{i}] <- {net}")
                continue
            pin = f"{port}[{i}]" if len(nets) > 1 else port
            lines.append(f'LOCATE COMP "{pin}" SITE "{ball}";')
            lines.append(f'IOBUF PORT "{pin}" IO_TYPE=LVCMOS33;')

    lines.append("")
    lines.append("# ---------------------------------------------------------------------------")
    lines.append("# TODO before a releasable bitstream:")
    lines.append("#  * IO_TYPE per bank - confirm each bank's VCCO (3V3/2V5/1V8) from the")
    lines.append("#    schematic; RGMII and ADC pins may need LVCMOS25 or DDR cells.")
    lines.append("#  * RGMII DDR: CrossLink DDR is only available in Bank 1 and Bank 2, so")
    lines.append("#    every RGMII ball above must be in Bank 1/2 (Bank 0 is SDR-only).")
    lines.append("#  * Timing: create_clock for clk_100m_in and the PLL's 125 MHz output.")

    open(OUT, "w").write("\n".join(lines) + "\n")
    print(f"wrote {OUT}  ({len(lines)} lines)")
    if missing:
        print("MISSING NETS (not found on the U20 footprint):")
        for m in missing:
            print("  " + m)
    return 0


if __name__ == "__main__":
    sys.exit(main())
